databases:
  - name: budget-app-prod
    databaseName: budget_app_prod_cqjp
    user: budget_app_prod_cqjp_user

services:
  - type: web
    name: budget-app-web-service
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-app-prod
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false